### ISSUE TITLE
Combo khi lớn hơn 9 sẽ bị vòng ngược về 0 (?) và lên lại 1.

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#10]
![image](https://user-images.githubusercontent.com/32929093/232324200-830cfcf5-8dc3-40e0-89f5-ae3adaf35e72.png)

Nói chung là hỗ trợ combo hơn 2 chữ số.

Sau 9 phải là 10 owo

**Comment by FukutoTojido** [comment]
Fixed in 0f710402c3452e70cceca9761389ad7a25079231
