### ISSUE TITLE
Ẩn title dưới playfield

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#11]
Khi playfield có object đè lên trên phần tiêu đề thì nên làm mờ hoặc ẩn cái tiêu đề đi, làm sao không chắn cái object là được. Nếu cao siêu thì ông làm ẩn chỉ cái chữ đi như cái vương miệng trong teamvs multi của osu ấy, làm mờ cho đẹp càng tốt, không thì đơn giản nhất kéo cái sắp xếp trục z của thằng title thấp hơn playfield cho object đè lên trên chữ là được.
À ừ thêm lựa chọn ẩn metadata vì tại sao không :))

![image](https://user-images.githubusercontent.com/32929093/232324686-fe8c25f4-2d38-42ef-9160-22af82995b79.png)
Trông sẽ na ná thế này
![out](https://user-images.githubusercontent.com/32929093/232327462-bf371551-d1f6-43b2-baf0-1ee91760acc0.png)

**Comment by honguyenminh** [comment]
Lười lắm thì cứ
![out](https://user-images.githubusercontent.com/32929093/232327567-e880747a-edb7-4d2b-9c0e-09c49f2fab7a.png)

Không thì cứ có object là blur hết cả cái text luôn cũng được

**Comment by FukutoTojido** [comment]
Đã đẩy metadata xuống dưới canvas trong 5e03a757b76b059f5cc0f863891abe1352d38ec4
Mặc dù ý tưởng blur khá là hay nhưng trên thực tế những hitObject được vẽ trên canvas với các DOM Element còn lại là hoàn toàn tách biệt và không thể xử lý các hitObject đấy như các DOM Element thông qua CSS hay JS.
