### ISSUE TITLE
More beatmap provider

### ISSUE THREAD

**Issue by FoxeiZ** [FukutoTojido/beatmap-viewer-how#16]
_this is an enhancement, not an issue_

Như tiêu đề, anh có nghĩ là cần thêm 1 vài beatmap mirror khác không do user (như em chẳng hạn) bị VNPT'ed và việc download beatmap cực kì lâu, nhưng các mirror khác lại bình thường (có thể do server nerinyan bị overloaded, who knows).

Hoặc là có thể cho import từ file osz, cũng là 1 cách.

**Comment by FukutoTojido** [comment]
Hello, sorry vì phản hồi trễ do không hiểu sao Gmail tôi bị chậm. 
Nerinyan đang là lựa chọn tốt nhất ở thời điểm hiện tại bởi vì một số lý do sau:
- Nerinyan luôn update các beatmap mới nhất so với các mirror khác
- Chimu.moe đã từng là một lựa chọn cho đến khi tôi nhận thấy số lượng beatmap không nhiều, vẫn có nhiều map bị thiếu
- Sayobot.cn tuy cũng có khá nhiều map up-to-date nhưng lại gặp khá nhiều vấn đề về timeout trong quá trình dev
Và thực tế với việc bản thân cũng là một người dùng VNPT, tôi đánh giá Nerinyan khá ổn so với mặt bằng chung, tốc độ vẫn ổn, và nếu có issue thì tôi có thể liên hệ trực tiếp với dev của Nerinyan để xử lý.
Trong tương tai tôi sẽ thêm drag-n-drop / import beatmap local. Nó đã ở trong development road nhưng dạo này tôi khá bận nên chưa thể tiếp tục :')

**Comment by FukutoTojido** [comment]
Added 2 more beatmap providers + custom beatmap provider also
