### ISSUE TITLE
Reverser slider không có, ờ, tiếng cho reverse end.

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#3]
Như tiêu để, trong các reverse slider hoặc buzz slider chỉ có tiếng ở head với tail, mấy reverse end mất tiếng hết.

**Comment by honguyenminh** [comment]
Ông nên để Todo với bug trong cái issue này, label chúng nó lại, đừng để trong readme.

**Comment by FukutoTojido** [comment]
Yeah tui có để ý đến điều đó và cũng sẽ có dự định làm trong tương lai gần.

**Comment by FukutoTojido** [comment]
Sẽ được sửa khi branch WebGL hoàn thiện
