### ISSUE TITLE
Thêm tính năng lấy luôn beatmapid và timestamp từ url query

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#6]
Không biết thằng github pages có cho không, nhưng nếu được thì nên tận dụng cái query trong url. Ví dụ ``?t=xxxx`` sẽ tua sẵn đến ms thứ xxxx, ``?b=kkkkkkkkkkk" sẽ mở luôn beatmapid kkkkkkkkkkk.

Thế thì ta có thể share map cho nhau bằng cách gửi link kiểu handsome.com/viewer?b=3694755&t=13568 để chia sẻ map có id 3694755 và tua sẵn đến mili giây thứ 13568

Thêm cả nút trong UI kiểu "Share this moment" thì càng tốt.

**Comment by FukutoTojido** [comment]
Lấy bID từ URL đã được tui cân nhắc một vài lần nhưng tạm thời tui sẽ để nó qua một bên trước để hoàn thiện về phần render.

**Comment by FukutoTojido** [comment]
Done in 32f41da1bd56b1096cd254a1fc62c2d20821a077
