### ISSUE TITLE
Bug khi resize cửa sổ

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#7]
# 1. Khi cửa sổ đủ điều kiện để UI nó bỏ qua border như gần cuối video, slider body sẽ bị quái thai và bị clip bởi khung hình chữ nhật khi slider ball kéo qua.

![Capture](https://user-images.githubusercontent.com/32929093/232322745-c2eccc43-6c0d-4e47-83cd-dc99092f1e56.PNG)

https://user-images.githubusercontent.com/32929093/232322964-609a7fd6-372e-4895-bb75-2a5d41e57656.mp4

# 2. Khi tạm dừng rồi resize, playfield không tự scale theo mà chờ đến khi play lại mới scale lại. Maybe intentional though.

https://user-images.githubusercontent.com/32929093/232323135-b8971737-4f97-4428-ab56-cda65bb21996.mp4

**Comment by FukutoTojido** [comment]
> Khi cửa sổ đủ điều kiện để UI nó bỏ qua border như gần cuối video, slider body sẽ bị quái thai và bị clip bởi khung hình chữ nhật khi slider ball kéo qua.

Bug này xuất phát từ việc tui set cứng độ dày của sliderball, dẫn đến khi render ở độ phân giải khá là thấp như trong video thì phần độ dày đó sẽ bị phình ra. 

> Khi tạm dừng rồi resize, playfield không tự scale theo mà chờ đến khi play lại mới scale lại. Maybe intentional though.

Intentional, nhưng mà trong tương lai tui sẽ tìm cách kiểm tra thay đổi width / height của window để update khi không play.

**Comment by honguyenminh** [comment]
> Intentional, nhưng mà trong tương lai tui sẽ tìm cách kiểm tra thay đổi width / height của window để update khi không play.

Hoặc là ông có thể nhích lên 1 tick rồi nhích xuống lại :))
Hacky but simple and works :))

**Comment by FukutoTojido** [comment]
> Khi cửa sổ đủ điều kiện để UI nó bỏ qua border như gần cuối video, slider body sẽ bị quái thai và bị clip bởi khung hình chữ nhật khi slider ball kéo qua.

Đã giải quyết được phần đầu thông qua việc force render ở 1080p rồi scale lại ngang với resolution của device trong 5e03a757b76b059f5cc0f863891abe1352d38ec4

**Comment by FukutoTojido** [comment]
nvm phần thứ hai được giải quyết trong c290a929d6312daa1213d719999cbef066a6b3e1
