### ISSUE TITLE
Cửa sổ ở chế độ nhỏ có thể che đi player control mà không scroll xuống được

### ISSUE THREAD

**Issue by honguyenminh** [FukutoTojido/beatmap-viewer-how#8]
https://user-images.githubusercontent.com/32929093/232323612-2f79340b-6456-43d6-937f-3d453e1cd862.mp4

**Comment by FukutoTojido** [comment]
Tui không nghĩ web này sẽ thực sự được sử dụng trong trong trường hợp low res + aspect ratio 1 / 1 như thế này nên có lẽ sẽ không cần phải fix cho lắm. Tạm thời tui sẽ chưa cân nhắc lại bởi vì việc nó không scroll được trong trường hợp này thực ra là intentional.
